version: "3.9"
services:
  nginx:
    build: ./containers/nginx
    depends_on:
      - landing-server
    networks:
      - main
      - instances
    ports:
      - "80:80"

  landing-server:
    build: ./containers/landing
    depends_on:
      - db
      - redis
    networks:
      - main
  
  db:
    build: ./containers/postgres
    networks:
      - main
    volumes:
      - "data:/var/lib/postgresql/data"

  redis:
    build: ./containers/redis
    networks:
      - main
    ports:
      - "6379:6379"

  control:
    build: ./containers/control
    depends_on:
      - db
      - redis
    networks:
      - main
    ports:
      - "8080:80"

  submit:
    build: ./containers/submit
    depends_on:
      - db
    networks:
      - main
  
volumes:
  data:
    name: devob-data

networks:
  main:
    driver: bridge
  instances:
    driver: bridge
    internal: true
